language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio lib install
script:
- platformio run
before_deploy:
- "./.prepare_release"
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: cejQW325lhBBvRy8aaW8SkLAB4vZ+0vo1RKAqRZJkJK9a742+WwG5eDipECaX5KgKYy5DkOyvJXPodMKThj1NzOlr6dclsGgE2F1qFQ8+HP8LloGJqAKahErlyxamGaY9AippkR/yf2YFW85EhTM5qhAiPq2bO2ln0Z9SucYz087/8wtnINVgPTrvioOJDB25oh1+OgUJmcMfN43EThJ8VjwVowXqdvRGJQ/VbsS+cBBlZyxxHTVTrMpV4xMVqT5dtFB1Ny8IGSg3myz3Hs89GC00h1jjipXewKVwDMkZUYVfgxaSfkzkm88I0Q9E9p8+GlL2IZQ9ly2KsmKLXynNq60KuiVIuFkI+6V4gajG7gxNFK9efzJ3zfTRsutxckmj3lDjC+vUnMPo2KlLk/Ko/2DCpLFSlrO0x5aq+LrwF+3UNZFFmpvuG/UtyHod5/3UCa2IhRfQUerFFD7mWpSrA3vvZEz+XmWVXx8VkSBN1HIejhN8h+q0goU+lAAywiQppfYk5R+W2p+vXXsenFdw+hwG5zrG0p7pnvvVnXgJl8yyHRMIFin94zsyAM8BaCwNQ7zbEIy8faU24OxofNx4qalf+xs7VkcVYrDOYwtj+Or3ZKrrPVCRnsC4DsfO5g4jeuJDvMaZmk6QB6eif0Bn3u1iE8e0Ygm6L1RxJqw8pc=
  file_glob: true
  skip_cleanup: true
  file: dist/*.bin
  on:
    repo: sidoh/esp8266_thermometer
    tags: true
